# このconfigは、 dockerでMisskey本体を起動せず、 redisとpostgresql などだけを起動します

services:
  valkey:
    restart: always
    image: valkey/valkey:9.0.0-alpine3.22
    ports:
      - "6379:6379"
    volumes:
      - valkey:/data
    healthcheck:
      test: "valkey-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: groonga/pgroonga:4.0.4-alpine-18
    ports:
      - "5432:5432"
    env_file:
      - .config/docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    volumes:
#      - meilisearch:/meili_data

volumes:
  valkey:
  pgdata:
  # meilisearch:
